//===========================
#define TEAM_EURASIA 0
#define TEAM_ARAB 1
#define TEAM_SOVIET 2
#define TEAM_USA 3
#define TEAM_AUS 4
#define TEAM_MARVEL 5
#define TEAM_MERC 6
#define MAX_TEAMS 7
#define TEAM_NONE 8
#define SpamLimit (3000)
#define MAX_ZONE_NAME 28
//-----------------------------------

#define TEAM_ZONE_EURASIA_COLOR 0x15FF0055 // Green
#define TEAM_ZONE_ARAB_COLOR 0xFFAF0255// Orange
#define TEAM_ZONE_SOVIET_COLOR 0xFF000055 //Red
#define TEAM_ZONE_USA_COLOR 0x0080FF55 //Bright Blue
#define TEAM_ZONE_AUS_COLOR 0x69006955 //purple color
#define TEAM_ZONE_MARVEL_COLOR 	0xF4A06877 //purple color

#define TEAM_EURASIA_COLOR 0x15FF00FF // Bright Green
#define TEAM_ARAB_COLOR 0xFFAF02FF// Orange
#define TEAM_SOVIET_COLOR 0xFF0000FF //Bright Red
#define TEAM_USA_COLOR 0x0080FFFF //Bright Blue
#define TEAM_AUS_COLOR 0x690069FF //purple color
#define TEAM_MARVEL_COLOR 0xF4A06877//brown color
#define TEAM_INDIA_COLOR  0xF4A06877
